### ISSUE TITLE
Post component missing source_url

### ISSUE THREAD

**Issue by brvith** [estacks/king-angular#3]
While testing, wp-post.component.html, says missing image source_url. I believe it should be look under features media.

`<div class="view overlay">
          <img *ngIf="post._embedded" class="card-img-top" [src]="post._embedded['wp:featuredmedia']['0'].source_url" 
          [alt]="post._embedded['wp:featuredmedia']['0'].slug">
          <a [href]="post._embedded['wp:featuredmedia']['0'].source_url" target="_blank">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>
`

**Comment by estacks** [comment]
I forgot to put it in the README but I used the `Better Rest API Featured Images` plugin to make sure that JSON field is properly populated. WP page is here: https://wordpress.org/plugins/better-rest-api-featured-images/

Thank you for bringing it up, I've fixed the README!

**Comment by brvith** [comment]
Thanks
